___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [2]:
print(np.__version__)

1.19.5


Створити вектор з 10 елементів, заповнений одиницями:

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [4]:
np.arange(0, 11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [5]:
nums = 0
np.full((5, 5), nums)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [9]:
somevector = np.random.randint(20, size = (1,21))
somevector

array([[19, 16,  2,  5, 19,  3,  0,  4, 18,  3,  7, 16, 16, 12, 16,  4,
         6,  0,  7, 13, 17]])

Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [12]:
print(np.mean(somevector))
print(np.median(somevector))
print(np.std(somevector))

9.666666666666666
7.0
6.628461958592501


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [14]:
matrix_A = np.random.randint(20, size = (4,2))
matrix_B = np.random.randint(20, size = (2,2))

In [15]:
matrix_A

array([[16, 10],
       [ 9, 14],
       [ 2, 11],
       [19,  2]])

In [16]:
matrix_B

array([[ 7, 11],
       [ 3,  0]])

In [17]:
matrix_C = np.reshape(matrix_B, (4,1)) * matrix_A
matrix_C

array([[112,  70],
       [ 99, 154],
       [  6,  33],
       [  0,   0]])

Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

Дано матрицю. Знайти ранг матриці:

In [2]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

Знайти визначник матриці:

In [3]:
np.linalg.matrix_rank(a)

3

Знайти власні значення та власні вектори матриці: 

In [4]:
np.linalg.det(a)

440.0000000000002

In [5]:
ba, ca = np.linalg.eigh(a)

In [6]:
ba#власні значення

array([-14.30540864,  -4.34740072,  23.65280936])

In [7]:
ca#власні вектори

array([[ 0.15315575,  0.88160309,  0.44645191],
       [ 0.63674998, -0.43353159,  0.6376518 ],
       [-0.75570681, -0.18661821,  0.62775861]])

Знайдіть число, що найчастіше зустрічається в масиві:

In [8]:
a = np.random.randint(0,10,50)

In [9]:
np.argmax(np.bincount(a))

6

Виведіть лише парні числа, що діляться на 5:

In [10]:
a = np.random.randint(0,10,50)

In [11]:
l = [i for i in a if i%5 == 0]
print(*l)

5 5 0 0 5 0 5 0 0 5 5 5 5


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [12]:
A = [[2, 5], [1, -10]]
B = [[1], [3]]

In [13]:
A_A = np.array(A)
inv_A = np.linalg.inv(A_A)
print(inv_A)

[[ 0.4   0.2 ]
 [ 0.04 -0.08]]


In [14]:
B_B = np.array(B)
X = np.linalg.inv(A_A).dot(B_B)
print(*X)

[1.] [-0.2]


In [15]:
print(2*1 + 5*(-0.2))
print(1 - 10*(-0.2))

1.0
3.0
